### ISSUE TITLE
is there an estimation of inference time per frame?

### ISSUE THREAD

**Issue by malfonsoarquimea** [JADGardner/neusky#1]
we are planning to use your method as a baseline for a research project we are carrying out. Could you share approximate inference times using whichever GPUS you used?
As per equation 1, I understand that the required number of inferences per pixel is:
per sample in the ray:

- 1 inference to the sdf net to get the sigmas/alphas/weights for the alpha composition
- 1 inference to the albedo net to get the albedo color
- per direction (642 in total)
  -  1 inference of the reni++ network to obtain the hdr light coming from that direction
  -  1 inference to the ddf to obtain visibility
  - normal vector computed from the sdf
Is there something I am missing?
thanks very much in advance!

**Comment by JADGardner** [comment]
Hi, thanks for your interest in our work!

So we have multiple samples per ray but only sample our visibility network and RENI++ once for each ray at the sample on the object's surface and then distribute these back along the remaining samples along the ray. As the density converges on the surface this approximation becomes more and more accurate.

On my local RTX 3080 Ti Laptop GPU, inference of a 1280x847 image takes around 6 minutes, on an A100 around 3 minutes.

**Comment by malfonsoarquimea** [comment]
thanks very much! If we end up building upon your project (which looks amazing tbh) we will try to make it faster!
thanks again !
