### ISSUE TITLE
which version of nerfstudio was used?

### ISSUE THREAD

**Issue by malfonsoarquimea** [JADGardner/neusky#3]
I am trying to build a docker image to run Neusky. To build this, I am using a nerfstudio docker base image but I haven't had any success in making it run with either 0.3.4, 1.0.0, or 1.0.1

**Comment by JADGardner** [comment]
Hi, thanks for your question and interest in NeuSky!

It should be version 0.3.4 but RENI++ does require some additional libraries that are not included in the nerfstudio docker base image, libopenexr-dev and openexr, which might be causing an issue. And nerfstudio may have been updated in such a way to cause an issue.

I've added a Dockerfile to this repo that should contain everything needed to install NeuSky and I've pushed a build of this to Dockerhub [here](https://hub.docker.com/r/jadgardner/neusky). Inside this container you'll then just need to clone and install NeuSky using:

```bash
git clone https://github.com/JADGardner/neusky.git
cd neusky
python3.10 -m pip install -e .
```

You'll still need to download the RENI++ models using the script in the ns_reni repository (which I now notice I didn't have as an instruction in the README and will update this):

```bash
python3 ns_reni/scripts/download_models.py output/model/path/
```
And update this line in the config for NeuSky to point to this directory:

https://github.com/JADGardner/neusky/blob/bdf689b8b23a9fc38144e789686edcb161b512e7/neusky/configs/neusky_config.py#L150

Let me know if you have any other issues.

**Comment by malfonsoarquimea** [comment]
Hi! Thanks a lot!! I finally managed to create a working Docker image by building my own nerfstudio Docker image, based on a specific commit from the nerfstudio repo (commit 581ba95eabec3057b477824c87b7dba6fcc565f9) and adding neusky and reni++ on top of that. I believe the issue was that the version of nerfstudio used to develop Neusky's codebase falls somewhere between 0.3.4 and 1.0.0. Neusky is coded to work with the viewer in nerfstudio 0.3.4, but it also needs to be used with the RayGenerator implementation present in version 1.0.0, where the camera optimizer is not passed to the ray generator. Anyway, thanks a ton, I'll probably end up using your Docker image as the base for our project. Keep up the great work, you're a champ!
